"""PRDemo binary file parser for Project Reality: BF2.

Parses .PRdemo (tracker) files generated by PR game servers,
extracting player stats, kills, vehicles, revives, flags, and round info.

Protocol reference: github.com/emilekm/go-prbf2/prdemo
"""

from .types import MessageType
from .decode import DemoReader
from .messages import (
    ServerDetails,
    PlayerAdd,
    PlayerRemove,
    PlayerUpdate,
    Kill,
    Chat,
    Revive,
    KitAllocated,
    VehicleAdd,
    VehicleUpdate,
    VehicleDestroyed,
    FobAdd,
    FobRemove,
    RallyAdd,
    RallyRemove,
    FlagUpdate,
    Flag,
    CacheAdd,
    CacheRemove,
    CacheReveal,
    IntelChange,
    SquadName,
    RoundEnd,
    Ticks,
    ProjAdd,
    ProjUpdate,
    ProjRemove,
)
from .parser import parse_demo, parse_demo_file, RoundStats

__all__ = [
    "MessageType",
    "DemoReader",
    "ServerDetails",
    "PlayerAdd",
    "PlayerRemove",
    "PlayerUpdate",
    "Kill",
    "Chat",
    "Revive",
    "KitAllocated",
    "VehicleAdd",
    "VehicleUpdate",
    "VehicleDestroyed",
    "FobAdd",
    "FobRemove",
    "RallyAdd",
    "RallyRemove",
    "FlagUpdate",
    "Flag",
    "CacheAdd",
    "CacheRemove",
    "CacheReveal",
    "IntelChange",
    "SquadName",
    "RoundEnd",
    "Ticks",
    "ProjAdd",
    "ProjUpdate",
    "ProjRemove",
    "parse_demo",
    "parse_demo_file",
    "RoundStats",
]
