"""Nombres oficiales de vehículos (HudName) del Map Gallery / realitytracker
(https://github.com/yossizap/realitytracker, data.json). Fuente primaria de
aliases.resolve_vehicle — más preciso que nuestros nombres hechos a mano.
Regenerar: extraer data.json["vehicles"] → {code: HudName}.
"""

HUD_NAMES = {
    '2cm_flak38': '2cm Flak 38',
    '2cm_flakvierling_38': '2cm Flakvierling 38',
    '37mm_m1939': '37mm M1939 (61-K)',
    '45mm_m1937': '45mm M1937',
    '88mm_flak_18_s': '8.8cm Flak 18',
    '88mm_flak_18_u': '8.8cm Flak 18',
    'aa_m167': 'M167',
    'aaa_rh202': 'Rheinmetall Rh 202',
    'aaa_rh202_atc': 'Rheinmetall Rh-202',
    'apc_bmp2_passenger1': 'killed',
    'apc_lav25_rearpassenger_r': 'LAV-25',
    'apc_namer_passenger1': 'Namer',
    'apc_vbci_passenger1': 'VBCI',
    'arf_acv_technical': 'Aerial Recon',
    'arf_tnk_t55': 'T-55',
    'arf_tnk_t55_machinegunner': 'T-55',
    'arg_apc_lvtp7': 'LVTP-7',
    'arg_jep_vwt1': 'Volkswagen Type 1',
    'arg_jet_a1h': 'A-1H Skyraider',
    'arg_jet_a1h_objective': 'arg_jet_a1h_objective',
    'arg_jet_a4b': 'A-4B Skyhawk',
    'arg_jet_a4c': 'A-4C Skyhawk',
    'arg_jet_a4q': 'A-4Q Skyhawk',
    'arg_jet_dagger': 'IAI Dagger A',
    'arg_jet_dagger_cas': 'IAI Dagger A CAS',
    'arg_jet_mirage3ea': 'Mirage IIIEA',
    'arg_jet_mirage3ea_as': 'Mirage IIIEA AS',
    'arg_the_chinook_ch47c': 'Chinook CH-47C',
    'arg_the_uh1h': 'UH-1H Iroquois',
    'arg_trk_logistics': 'M35 Logistics',
    'arg_trk_support': 'M35 2.5 Ton',
    'ats_hj8': 'HJ-8',
    'ats_hj8_ndl': 'HJ-8',
    'ats_spg9_vehicle': 'SPG-9',
    'ats_spg9_vehicle_uaz': 'SPG-9',
    'ats_tow': 'BGM-71 TOW',
    'ats_tow_ndl': 'BGM-71 TOW',
    'au_tnk_t55': 'T-55',
    'au_tnk_t55_machinegunner': 'T-55',
    'boat_rib': 'RHIB',
    'boat_rib_agl_mk19': 'RHIB',
    'boat_rib_gpmg_anf1': 'RHIB',
    'boat_rib_gpmg_c6': 'RHIB',
    'boat_rib_gpmg_l7a2': 'RHIB',
    'boat_rib_gpmg_m240b': 'RHIB',
    'boat_rib_gpmg_mg3': 'RHIB',
    'boat_rib_gpmg_pkp': 'RHIB',
    'boat_rib_hmg_m2': 'RHIB',
    'boat_rib_hmg_pkm': 'RHIB',
    'boat_rib_unarmed': 'RHIB',
    'cargoship_atlantic_conveyor': 'SS Atlantic Conveyor',
    'cargoship_atlantic_conveyor_skirmish16': 'SS Atlantic Conveyor',
    'cf_acv_lav3cpv': 'Aerial Recon',
    'cf_apc_lav3': 'LAV-3',
    'cf_apc_lav3_bf2': 'LAV-3',
    'cf_ifv_coyote': 'Coyote Recon Vehicle',
    'cf_ifv_coyote_bf2': 'Coyote Recon Vehicle',
    'cf_jep_gwagon': 'Mercedes G-Wagen',
    'cf_jep_gwagon_support': 'Mercedes G-Wagen Support',
    'cf_jet_cf18': 'CF-188A Hornet',
    'cf_jet_cf18_cas': 'CF-188A Hornet CAS',
    'cf_jet_cf18_flyover': 'CF-188A Hornet',
    'cf_jet_cf18_sp': 'CF-188A Hornet',
    'cf_the_ch146': 'CH-146 Griffon',
    'cf_the_ch146_c6': 'CH-146 Griffon',
    'cf_the_ch146_m134': 'CH-146 Griffon CAS',
    'cf_the_chinook': 'CH-147F Chinook',
    'cf_the_uh1n': 'CH-135 Twin Huey',
    'cf_the_uh1n_c6': 'CH-135 Twin Huey',
    'cf_the_uh1n_sp': 'UH-1N Twin Huey',
    'cf_tnk_leo2a6': 'Leopard 2A6',
    'cf_tnk_leo2a6_bf2': 'Leopard 2A6',
    'cf_trk_logistics': 'MLVW Logistics',
    'cf_trk_support': 'MLVW',
    'ch_aav_type95': 'PGZ-04 SPAAG',
    'ch_acv_wz551': 'Aerial Recon',
    'ch_ahe_z10': 'Z-10',
    'ch_ahe_z10_sp': 'Z-10',
    'ch_ahe_z9wa': 'Z-9WA Haitun',
    'ch_ahe_z9wa_23mm_guns': 'Z-9WA Haitun 23mm',
    'ch_ahe_z9wa_23mm_guns_sp': 'Z-9WA Haitun 23mm',
    'ch_ahe_z9wa_hf25': 'Z-9WA Haitun HF-25',
    'ch_ahe_z9wa_hf25_sp': 'Z-9WA Haitun HF-25',
    'ch_ahe_z9wa_hf7d': 'Z-9WA Haitun HF7D',
    'ch_ahe_z9wa_hf7d_sp': 'Z-9WA Haitun HF7D',
    'ch_ahe_z9wa_hj8': 'Z-9WA Haitun HJ-8',
    'ch_apc_wz551': 'ZSL-92 25mm',
    'ch_apc_wz551_bf2': 'ZSL-92 25mm',
    'ch_apc_wz551a': 'ZSL-92A',
    'ch_apc_zbl08': 'ZBL-08',
    'ch_atm_wz550': 'WZ550',
    'ch_boat': 'Landing Boat',
    'ch_ifv_type86': 'ZBD-86A',
    'ch_ifv_type86_bf2': 'ZBD-86A',
    'ch_ifv_wz551b': 'ZSL-92B 30mm',
    'ch_ifv_zbl08': 'ZBL-08',
    'ch_jep_mengshi': 'Dongfeng Mengshi CSK131',
    'ch_jep_mengshi_support': 'Dongfeng Mengshi CSK131 Support',
    'ch_jep_paratrooper': 'Norinco FAV',
    'ch_jep_uaz': 'BJ2020',
    'ch_jep_vn3': 'VN-3',
    'ch_jet_fantan': 'Q-5 Fantan',
    'ch_jet_j10': 'J-10 Firebird',
    'ch_jet_j10_sp': 'J-10 Firebird',
    'ch_jet_j11b': 'J-11B Flanker-L',
    'ch_jet_su30': 'Su-30MKK Flanker-G',
    'ch_jet_su30_sp': 'Su-30MKK Flanker-G',
    'ch_ship_type75_lpd_atc': 'Aerial Recon',
    'ch_the_mi17': 'Mi-17 Hip-H',
    'ch_the_mi171e': 'MI-171E',
    'ch_the_mi17_sp': 'Mi-17 Hip-H',
    'ch_the_z8': 'Z-8KA',
    'ch_the_z9b': 'Zhi-9B',
    'ch_tnk_type98': 'ZTZ-98',
    'ch_tnk_type98_bf2': 'ZTZ-98',
    'ch_tnk_type98_cupolabase': 'ZTZ-98',
    'ch_tnk_ztl11': 'ZTL-11',
    'ch_tnk_ztl11_bf2': 'ZTL-11',
    'ch_tnk_ztz99': 'ZTZ-99 II',
    'ch_tnk_ztz99_bf2': 'ZTZ-99 II',
    'ch_tnk_ztz99_cupolabase': 'ZTZ-99 II Gunner',
    'ch_trk_logistics': 'Dongfeng EQ1108 Logistics',
    'ch_trk_support': 'Dongfeng EQ1108',
    'civ_aav_uralzu232': 'Ural-4320 ZU-23-2',
    'civ_atm_technical': 'SPG-9 Technical',
    'civ_atm_technical_militia': 'SPG-9 Technical',
    'civ_atm_technical_rocket': 'Rocket Technical',
    'civ_bik_atv': 'All-Terrain Vehicle',
    'civ_bik_atv_laser': 'All-Terrain Vehicle',
    'civ_bik_dirtbike': 'Dirtbike',
    'civ_bik_hondacb500': 'Honda CB500',
    'civ_jep_buick': 'Buick',
    'civ_jep_car': 'Civilian Car',
    'civ_jep_car_black': 'Civilian Car',
    'civ_jep_car_blue': 'Civilian Car',
    'civ_jep_car_bomber': 'Car Bomb',
    'civ_jep_car_bomber_black': 'Car Bomb',
    'civ_jep_car_bomber_black_uparmored': 'Armored Car Bomb',
    'civ_jep_car_bomber_blue': 'Car Bomb',
    'civ_jep_car_bomber_blue_uparmored': 'Armored Car Bomb',
    'civ_jep_car_bomber_uparmored': 'Armored Car Bomb',
    'civ_jep_car_bomber_white': 'Car Bomb',
    'civ_jep_car_bomber_white_uparmored': 'Armored Car Bomb',
    'civ_jep_car_white': 'Civilian Car',
    'civ_jep_forklift': 'Industrial Forklift',
    'civ_jep_support': 'Support Technical',
    'civ_jep_support_arf': 'Support Technical',
    'civ_jep_support_fsa_logistics': 'Logistics Technical',
    'civ_jep_support_logistics': 'Logistics Technical',
    'civ_jep_support_militia': 'Support Technical',
    'civ_jep_technical': 'DShKM Technical',
    'civ_jep_technical2': 'DShKM Technical',
    'civ_jep_technical_black': 'M2HB Technical',
    'civ_jep_technical_blue': 'DShKM Technical',
    'civ_jep_technical_kord': 'KORD Technical',
    'civ_jep_technical_militia': 'DShKM Technical',
    'civ_jep_technical_red': 'M2HB Technical',
    'civ_jep_zastava900ak': 'Zastava 900AK Van',
    'civ_jep_zastava900ak_militia': 'Zastava 900AK Van',
    'civ_trk_dumpster': 'Dumpster Truck',
    'civ_trk_dumpster_bomber': 'Suicide Dumpster Truck',
    'civ_trk_dumpster_bomber_uparmored': 'Armored Suicide Dumpster Truck',
    'civ_trk_dumpster_uparmored': 'Armored Dumpster Truck',
    'civ_trk_semi': 'Semi Trailer Truck',
    'civ_trk_semi_bomber': 'Suicide Semi Trailer Truck',
    'civ_trk_zil131': 'ZIL 131',
    'civiliancar2': 'Civilian Car',
    'deployable_djigit': 'Djigit',
    'deployable_djigit_sp': 'Djigit',
    'deployable_dshk': 'DShK',
    'deployable_dshk_sp': 'DShK',
    'deployable_m1910': 'PM M.1910',
    'deployable_m1910_sp': 'PM M.1910',
    'deployable_m1919a6': 'M1919A6',
    'deployable_m1919a6_sp': 'M1919A6',
    'deployable_mg42': 'MG42',
    'deployable_mg42_sp': 'MG42',
    'deployable_mistral': 'Mistral',
    'deployable_mistral_sp': 'Mistral',
    'deployable_mortar_2b141_podnos': '2B14-1 Podnos',
    'deployable_mortar_2b141_podnos_sp': '2B14-1 Podnos',
    'deployable_mortar_m252': 'M252',
    'deployable_mortar_m252_ins': 'M252',
    'deployable_mortar_m252_ins_sp': 'M252',
    'deployable_mortar_m252_sp': 'M252',
    'deployable_mortar_pp87': 'PP-87',
    'deployable_mortar_pp87_sp': 'PP-87',
    'deployable_spg9': 'SPG-9',
    'deployable_stinger': 'Stinger',
    'deployable_stinger_sp': 'Stinger',
    'deployable_zu232': 'ZU-23-2',
    'deployable_zu232_sp': 'ZU-23-2',
    'fixed_mortar': 'M252',
    'fixed_mortar_ins': 'M252',
    'fr_acv_vab': 'Aerial Recon',
    'fr_ahe_sa342': 'SA-342 Gazelle',
    'fr_ahe_tiger': 'EC 665 Tigre HAP',
    'fr_ahe_tiger_sp': 'EC 665 Tigre HAP',
    'fr_apc_vab': 'VAB VTT',
    'fr_apc_vbci': 'VBCI',
    'fr_apc_vbci_bf2': 'VBCI',
    'fr_ats_milan': 'Milan',
    'fr_ats_milan_ndl': 'Milan',
    'fr_the_chinook': 'CH-147 Chinook',
    'fr_the_nh90': 'NH90 TTH',
    'fr_the_nh90_navy': 'NH90 NFH',
    'fr_the_panther': 'AS565 MB Panther',
    'fr_tnk_amx10rc': 'AMX-10RC',
    'fr_tnk_amx10rc_bf2': 'AMX-10RC',
    'fr_tnk_leclerc': 'AMX-56 Leclerc',
    'fr_tnk_leclerc_bf2': 'AMX-56 Leclerc',
    'fr_tnk_leclerc_cupola_gunner': 'AMX-56 Leclerc',
    'fr_trk_logistics': 'GBC 180 Logistics',
    'fr_trk_support': 'GBC-180',
    'fraas_mistral': 'Mistral',
    'fsa_ifv_bmp1': 'BMP-1',
    'fsa_ifv_bmp1_bf2': 'BMP-1',
    'fsa_jep_zastava900ak_logistics': 'Logistics Van',
    'fsa_tnk_t55': 'T-55',
    'fsa_tnk_t55_bf2': 'T-55',
    'fsa_tnk_t55_machinegunner': 'T-55',
    'fsa_tnk_t62': 'T-62',
    'fsa_tnk_t62_bf2': 'T-62',
    'fsa_tnk_t62_cupolagunner': 'T-62',
    'gb82_trk_logistics': 'MAN SV Logistics',
    'gb82_trk_support': 'MAN Support Vehicle',
    'gb_aav_stormer': 'Stormer HVM',
    'gb_acv_sultan': 'Aerial Recon',
    'gb_ahe_apache': 'Apache AH1',
    'gb_ahe_apache_sp': 'Apache AH1',
    'gb_apc_warrior': 'FV 510 Warrior',
    'gb_apc_warrior_bf2': 'FV 510 Warrior',
    'gb_apc_warrior_cage': 'FV 510 Warrior',
    'gb_carrier_illustrious': 'HMS Illustrious',
    'gb_carrier_invincible': 'HMS Invincible',
    'gb_ifv_scimitar': 'FV 107 Scimitar',
    'gb_ifv_scimitar_bf2': 'FV 107 Scimitar',
    'gb_ifv_scimitar_cage': 'FV 107 Scimitar',
    'gb_ifv_scorpion': 'FV101 Scorpion',
    'gb_ifv_scorpion_bf2': 'FV101 Scorpion',
    'gb_jep_landrover': 'Land Rover',
    'gb_jep_landrover_gmg': 'Land Rover GMG',
    'gb_jep_landrover_support': 'Land Rover Support',
    'gb_jep_panther': 'Panther CLV',
    'gb_jep_panther_alt': 'Panther CLV',
    'gb_jet_eurofighter': 'Eurofighter Typhoon',
    'gb_jet_eurofighter_sp': 'Eurofighter Typhoon',
    'gb_jet_harrier': 'Harrier GR.9',
    'gb_jet_harrier_gr3': 'Harrier GR.3 CAS GPB',
    'gb_jet_harrier_gr3b': 'Harrier GR.3 CAS LGB',
    'gb_jet_harrier_gr3c': 'Harrier GR.3 CAS Rockets',
    'gb_jet_harrier_gr9_asf': 'Harrier GR.9 ASF',
    'gb_jet_harrier_sp': 'Harrier GR.9',
    'gb_jet_seaharrier': 'Sea Harrier FRS.1 ASF',
    'gb_jet_seaharrier_mk17': 'Sea Harrier FRS.1 CAS',
    'gb_jet_tornadogr4_mw1': 'Tornado GR4',
    'gb_the_chinook': 'Chinook HC.4',
    'gb_the_chinook_ch1': 'Chinook HC1',
    'gb_the_gazelle': 'Gazelle AH.1',
    'gb_the_lynx': 'Lynx AH.7',
    'gb_the_lynx_ah9a': 'Lynx AH.9A',
    'gb_the_lynx_ah9a_hmg': 'Lynx AH.9A',
    'gb_the_lynx_ah9a_hmg_sp': 'Lynx AH.9A',
    'gb_the_lynx_ah9a_sp': 'Lynx AH.9A',
    'gb_the_lynx_alt': 'Lynx AH.7',
    'gb_the_lynx_l7a2': 'Lynx AH.7',
    'gb_the_lynx_l7a2_alt': 'Lynx AH.7',
    'gb_the_lynx_sp': 'Lynx AH.7',
    'gb_the_merlin': 'Merlin HC3',
    'gb_the_wessex': 'Wessex HU.5',
    'gb_tnk_challenger': 'FV4034 Challenger 2',
    'gb_tnk_challenger_alt': 'FV4034 Challenger 2',
    'gb_tnk_challenger_alt_bf2': 'FV4034 Challenger 2',
    'gb_tnk_challenger_bf2': 'FV4034 Challenger 2',
    'gb_tnk_challenger_mgcupolabase': 'FV4034 Challenger 2',
    'gb_trk_logistics': 'MAN SV Logistics',
    'gb_trk_logistics_cage': 'MAN SV Logistics',
    'gb_trk_support': 'MAN Support Vehicle',
    'ger_aav_flak38blitz': 'Opel Blitz Flak 38',
    'ger_acv_m557a2': 'Aerial Recon',
    'ger_acv_tent': 'Aerial Recon',
    'ger_ahe_tiger': 'EC 665 UH Tiger',
    'ger_ahe_tiger_sp': 'EC 665 UH Tiger',
    'ger_apc_251c': 'SdKfz 251C',
    'ger_apc_251c_1941': 'SdKfz 251C',
    'ger_apc_251c_1941_alt': 'SdKfz 251C',
    'ger_apc_251c_alt': 'SdKfz 251C',
    'ger_apc_fuchs': 'TPz Fuchs 1A8',
    'ger_apc_puma': 'Puma',
    'ger_ifv_231': 'SdKfz 231',
    'ger_ifv_231_bf2': 'SdKfz 231',
    'ger_ifv_233': 'SdKfz 233 Stummel',
    'ger_ifv_233_bf2': 'SdKfz 233 Stummel',
    'ger_ifv_puma': 'Puma IFV',
    'ger_ifv_puma_bf2': 'Puma IFV',
    'ger_jep_fennek_agl': 'Fennek 1A1 GMW',
    'ger_jep_fennek_mg3': 'Fennek 1A1 MG3',
    'ger_jep_gwagon_support': 'Mercedes G-Wagen',
    'ger_jep_gwagon_support_alt': 'Mercedes G-Wagen',
    'ger_jep_kubel': 'Kubelwagen',
    'ger_jet_bf109g6': 'Messerschmitt Bf-109',
    'ger_jet_eurofighter': 'Eurofighter Typhoon',
    'ger_jet_eurofighter_sp': 'Eurofighter Typhoon',
    'ger_jet_ju87b': 'Ju-87B Stuka',
    'ger_jet_tornadogr4_mw1': 'Tornado IDS',
    'ger_shp_lcvp': 'LCVP',
    'ger_shp_lcvp_bot': 'LCVP',
    'ger_the_nh90': 'NH90 TTH',
    'ger_the_uh1d': 'Bell UH-1D',
    'ger_the_uh1d_mg3': 'Bell UH-1D',
    'ger_tnk_leo2a6': 'Leopard 2A6',
    'ger_tnk_leo2a6_bf2': 'Leopard 2A6',
    'ger_tnk_p3j': 'Panzer III Ausf. J',
    'ger_tnk_p3j_bf2': 'Panzer III Ausf. J',
    'ger_tnk_p3j_commander': 'Panzer III Ausf. J',
    'ger_tnk_p4d': 'Panzer IV Ausf. D',
    'ger_tnk_p4d_bf2': 'Panzer IV Ausf. D',
    'ger_tnk_p4d_commander': 'Panzer IV Ausf. D',
    'ger_tnk_p4f2': 'Panzer IV Ausf. F2',
    'ger_tnk_p4f2_bf2': 'Panzer IV Ausf. F2',
    'ger_tnk_p4f2_commander': 'Panzer IV Ausf. F2',
    'ger_tnk_p6h': 'Panzer VI Tiger Ausf. E',
    'ger_tnk_p6h_bf2': 'Panzer VI Tiger Ausf. E',
    'ger_tnk_panther_a': 'Panzer V Panther Ausf. A',
    'ger_tnk_panther_a_bf2': 'Panzer V Panther Ausf. A',
    'ger_tnk_panther_a_commander': 'Panzer V Panther Ausf. A',
    'ger_tnk_stug3b': 'Stug III Ausf. B',
    'ger_tnk_stug3b_bf2': 'Stug III Ausf. B',
    'ger_trk_logistics': 'MAN SV Logistics',
    'ger_trk_logistics_ww2': 'Opel Blitz Logistics',
    'ger_trk_support': 'MAN Support Vehicle',
    'ger_trk_support_ww2': 'Opel Blitz',
    'idf_aav_m163': 'M163 Vulcan',
    'idf_acv_m557': 'Aerial Recon',
    'idf_ahe_apache': 'AH-64D Saraph',
    'idf_ahe_apache_sp': 'AH-64D Saraph',
    'idf_apc_m113': 'M113',
    'idf_apc_m113_logistics': 'M113 Logistics',
    'idf_apc_namer': 'Namer',
    'idf_jep_hmmwv': 'HMMWV SIYUR',
    'idf_jep_hmmwvopen': 'HMMWV SIYUR',
    'idf_jet_f15': "F-15I Ra'am",
    'idf_jet_f16': 'F-16C Barak',
    'idf_jet_f16_sp': 'F-16C Barak',
    'idf_the_uh60': 'UH-60L Yanshuf',
    'idf_the_uh60_sp': 'UH-60L Blackhawk',
    'idf_tnk_merkava': 'Merkava Mark IV',
    'idf_tnk_merkava_bf2': 'Merkava Mark IV',
    'idf_tnk_merkava_turret_mg_gunner': 'Merkava Mark IV',
    'idf_trk_logistics': 'M35 Logistics',
    'idf_trk_support': 'M35 2.5 Ton',
    'ifv_bmp2_passenger1': 'killed',
    'igla_djigit': 'Igla Djigit',
    'igla_djigit_atc': 'Igla Djigit',
    'mec_aav_gaskin': '9K31 Gaskin',
    'mec_aav_gopher': '9K35 Gopher',
    'mec_aav_shilka': 'ZSU-23-4 Shilka',
    'mec_aav_shilka_bf2': 'ZSU-23-4 Shilka',
    'mec_acv_btr60pu': 'Aerial Recon',
    'mec_ahe_ec635': 'EC635 Eurocopter',
    'mec_ahe_havoc': 'Mi-28N Havoc',
    'mec_ahe_havoc_sp': 'Mi-28N Havoc',
    'mec_ahe_mi24': 'Mi-35P Hind',
    'mec_ahe_mi24_light': 'Mi-35 Hind',
    'mec_ahe_mi24_light_sp': 'Mi-35 Hind',
    'mec_ahe_mi24_sp': 'Mi-35P Hind',
    'mec_ahe_sa341h': 'SOKO HN-45M Gama 2',
    'mec_apc_bmp2': 'BMP-2',
    'mec_apc_bmp2_bf2': 'BMP-2',
    'mec_apc_boragh': 'Boragh',
    'mec_apc_btr60': 'BTR-60PB',
    'mec_apc_btr60_bf2': 'BTR-60PB',
    'mec_apc_btr80': 'BTR-80',
    'mec_apc_btr80_alt': 'BTR-80',
    'mec_apc_btr80_bf2': 'BTR-80',
    'mec_apc_btr80a': 'BTR-80A',
    'mec_apc_btr80a_bf2': 'BTR-80A',
    'mec_apc_mtlb': 'MT-LB',
    'mec_apc_mtlb_30mm': 'MT-LB 6MB',
    'mec_apc_mtlb_30mm_bf2': 'MT-LB 6MB',
    'mec_apc_mtlb_hmg': 'MT-LB 6M',
    'mec_apc_mtplb': 'MTP-LB',
    'mec_atm_shturm': '9P149 Shturm-S',
    'mec_atm_spandrel': '9P148 Spandrel',
    'mec_atm_spandrel_bf2': '9P148 Spandrel',
    'mec_ats_milan': 'Milan',
    'mec_ats_milan_ndl': 'Milan',
    'mec_ifv_bmp2m': 'BMP-2M',
    'mec_ifv_bmp2m_bf2': 'BMP-2M',
    'mec_ifv_bmp3': 'BMP-3',
    'mec_ifv_bmp3_bf2': 'BMP-3',
    'mec_ifv_saladin': 'FV601 Saladin',
    'mec_ifv_scorpion': 'FV101 Scorpion',
    'mec_ifv_scorpion_bf2': 'FV101 Scorpion',
    'mec_jep_brdm2': 'BRDM-2',
    'mec_jep_brdm2_support': 'BRDM-2 Support',
    'mec_jep_dzik': 'AMZ DZIK-3',
    'mec_jep_uaz': 'UAZ-3151 Support',
    'mec_jep_uaz_mg': 'UAZ-3151',
    'mec_jet_mig29': 'MiG-29 Fulcrum',
    'mec_jet_mig29_sp': 'MiG-29 Fulcrum',
    'mec_jet_su22': 'Su-22 Fitter',
    'mec_jet_su22_sp': 'Su-22 Fitter',
    'mec_jet_su25a': 'Su-25 Frogfoot',
    'mec_jet_su25a_sp': 'Su-25 Frogfoot',
    'mec_the_mi17': 'Mi-17 Hip-H',
    'mec_the_mi17_sp': 'Mi-17 Hip-H',
    'mec_the_sa341h': 'SOKO HO-42',
    'mec_tnk_t55': 'T-55',
    'mec_tnk_t55_machinegunner': 'T-55',
    'mec_tnk_t72': 'T-72M',
    'mec_tnk_t72_bf2': 'T-72M',
    'mec_tnk_t72_mgcupolabase': 'T-72',
    'mec_tnk_t72s': 'T-72S1',
    'mec_tnk_t72s_alt': 'T-72S',
    'mec_tnk_t72s_alt_bf2': 'T-72S',
    'mec_tnk_t72s_alt_mgcupolabase': 'T-72',
    'mec_tnk_t72s_bf2': 'T-72S1',
    'mec_tnk_t72s_mgcupolabase': 'T-72',
    'mec_trk_logistics': 'Ural-4320 Logistics',
    'mec_trk_support': 'Ural-4320',
    'mg_vehicle': 'MG Vehicle',
    'mil_acv_technical': 'Aerial Recon',
    'mil_atm_uaz_spg': 'UAZ-3151 SPG-9',
    'mil_ifv_bmp1': 'BMP-1',
    'mil_ifv_bmp1_bf2': 'BMP-1',
    'mil_jep_uaz': 'UAZ-3151 Support',
    'mil_jep_uaz_logistics': 'UAZ-3151 Logistics',
    'mil_jep_uaz_mg': 'UAZ-3151',
    'mil_tnk_t55': 'T-55',
    'mil_tnk_t55_bf2': 'T-55',
    'mil_tnk_t55_machinegunner': 'T-55',
    'mil_tnk_t62': 'T-62',
    'mil_tnk_t62_bf2': 'T-62',
    'mil_tnk_t62_cupolagunner': 'T-62',
    'mil_tnk_t72': 'T-72A',
    'mil_tnk_t72_bf2': 'T-72A',
    'mil_tnk_t72_mgcupolabase': 'T-72',
    'mil_trk_logistics': 'Ural-4320 Logistics',
    'mil_trk_support': 'Ural-4320',
    'nl_aav_fennekswp': 'Fennek SWP',
    'nl_acv_boxer': 'Aerial Recon',
    'nl_ahe_apache': 'AH-64D Apache',
    'nl_ahe_apache_light': 'AH-64D Apache',
    'nl_ahe_apache_sp': 'AH-64D Apache',
    'nl_apc_boxer': 'Boxer PWV',
    'nl_apc_cv90': 'CV9035NL',
    'nl_apc_ypr50': 'YPR 765 PRI/I',
    'nl_apc_ypr50_gpmg': 'YPR 765 PRI/I GPMG',
    'nl_jep_bushmaster': 'Bushmaster PMV',
    'nl_jep_bushmaster_crows': 'Bushmaster PMV CROWS',
    'nl_jep_fennek': 'Fennek VWWRN',
    'nl_jep_gwagon_support': 'Mercedes-Benz G280',
    'nl_jep_landrover': 'Land Rover Defender 110XD WW',
    'nl_jet_f16': 'F-16C Fighting Falcon',
    'nl_jet_f16_cas': 'F-16C Fighting Falcon CAS',
    'nl_jet_f16_sp': 'F-16C Fighting Falcon',
    'nl_the_chinook': 'CH-47D Chinook',
    'nl_the_nh90': 'NH90 TTH',
    'nl_tnk_leo2a6': 'Leopard 2A6',
    'nl_tnk_leo2a6_bf2': 'Leopard 2A6',
    'nl_tnk_leo2a6_mgcupola': 'Leopard 2A6',
    'nl_trk_logistics': 'DAF YA-4442 Logistics',
    'nl_trk_support': 'DAF YA-4442',
    'nva_aav_zsu57': 'ZSU-57-2',
    'nva_apc_btr60': 'BTR-60PB',
    'nva_jep_uaz': 'UAZ-469 Support',
    'nva_jep_uaz_mg': 'UAZ-469',
    'nva_jet_mig21': 'MiG-21 Fishbed',
    'nva_the_mi17': 'Mi-17 Hip-H',
    'nva_the_mi17_sp': 'Mi-17 Hip-H',
    'nva_tnk_pt76': 'PT-76',
    'nva_tnk_t55': 'T-55',
    'nva_tnk_t55_machinegunner': 'T-55',
    'nva_trk_support': 'ZIL 131',
    'nva_trk_zis5': 'ZIS-5V Logistics',
    'obj_staticvehicle_type95': 'KILLMESSAGE_VEHICLE_type95',
    'obj_staticvehicle_wz551': 'killed',
    'pak36': '3.7cm PaK 36',
    'pak40': '7.5cm PaK 40',
    'pl_aav_shilka': 'ZSU-23-4 Shilka',
    'pl_aav_shilka_bf2': 'ZSU-23-4 Shilka',
    'pl_acv_star1466': 'Aerial Recon',
    'pl_ahe_mi24': 'Mi-24W Hind',
    'pl_ahe_mi24_sp': 'Mi-24W Hind',
    'pl_ahe_sokol': 'W-3W Sokol',
    'pl_apc_rosomak': 'KTO Rosomak',
    'pl_apc_rosomak_bf2': 'KTO Rosomak',
    'pl_atm_spandrel': '9P148 Spandrel',
    'pl_atm_spandrel_bf2': '9P148 Spandrel',
    'pl_ifv_bwp1': 'BWP-1',
    'pl_ifv_bwp1_bf2': 'BWP-1',
    'pl_jep_brdm2': 'BRDM-2',
    'pl_jep_dzik': 'AMZ DZIK-3',
    'pl_jep_hmmwv_uparmored': 'M1151 Up-Armored HMMWV',
    'pl_jep_hmmwv_uparmored_mk19': 'M1151 Up-Armored HMMWV MK19',
    'pl_jep_honker': 'Honker 2000',
    'pl_jep_skorpion': 'Honker Skorpion-3',
    'pl_jep_zbik': 'BRDM-2-M97 Zbik',
    'pl_jet_f16': 'F-16C Fighting Falcon',
    'pl_jet_f16_sp': 'F-16C Fighting Falcon',
    'pl_the_mi17': 'Mi-17 Hip-H',
    'pl_the_mi17_sp': 'Mi-17 Hip-H',
    'pl_the_sokol': 'W-3T Sokol',
    'pl_tnk_leopard2a4': 'Leopard 2A4',
    'pl_tnk_pt91': 'PT-91 Twardy',
    'pl_tnk_pt91_bf2': 'PT-91 Twardy',
    'pl_tnk_pt91_mgcupolabase': 'PT-91 Twardy',
    'pl_tnk_t72': 'T-72M',
    'pl_tnk_t72_bf2': 'T-72M',
    'pl_tnk_t72_mgcupolabase': 'T-72',
    'pl_trk_logistics': 'Star 1466 Logistics',
    'pl_trk_support': 'Star 944 Support',
    'ru_aav_gopher': '9K35 Gopher',
    'ru_aav_m3': 'M3A1 Halftrack M45',
    'ru_aav_shilka': 'ZSU-23-4 Shilka',
    'ru_aav_shilka_bf2': 'ZSU-23-4 Shilka',
    'ru_aav_tunguska': '9K22 Tunguska',
    'ru_acv_btr60pu': 'Aerial Recon',
    'ru_acv_tent': 'Aerial Recon',
    'ru_ahe_havoc': 'Mi-28N Havoc',
    'ru_ahe_havoc_sp': 'Mi-28N Havoc',
    'ru_ahe_ka29t': 'KA-29 CAS',
    'ru_ahe_ka29t_s8kom': 'KA-29 CAS S-8KOM',
    'ru_ahe_ka29t_s8kom_light': 'KA-29 CAS S-8KOM Light',
    'ru_ahe_ka29t_s8kom_upk23': 'KA-29 CAS S-8KOM UPK-23',
    'ru_ahe_ka29t_upk23': 'KA-29 CAS UPK-23',
    'ru_ahe_mi24': 'Mi-24P Hind-F',
    'ru_ahe_mi24_light': 'Mi-24V Hind-E',
    'ru_ahe_mi24_light_sp': 'Mi-24V Hind-E',
    'ru_ahe_mi24_sp': 'Mi-24P Hind-F',
    'ru_ahe_mi8amtsh': 'Mi-8 AMTSh CAS',
    'ru_ahe_mi8amtsh_s8kom': 'Mi-8 AMTSh S-8KOM',
    'ru_ahe_mi8amtsh_upk23': 'Mi-8 AMTSh UPK-23',
    'ru_ahe_mi8amtsh_upk23_s8kom': 'Mi-8 AMTSh UPK-23 S-8KOM',
    'ru_apc_bmp2': 'BMP-2',
    'ru_apc_bmp2_bf2': 'BMP-2',
    'ru_apc_btr60': 'BTR-60PB',
    'ru_apc_btr60_bf2': 'BTR-60PB',
    'ru_apc_btr80': 'BTR-80',
    'ru_apc_btr80_alt': 'BTR-80',
    'ru_apc_btr80_bf2': 'BTR-80',
    'ru_apc_btr80a': 'BTR-80A',
    'ru_apc_btr80a_bf2': 'BTR-80A',
    'ru_apc_btr82am': 'BTR-82AM',
    'ru_apc_btr82am_bf2': 'BTR-82AM',
    'ru_apc_m3': 'M3A1 Halftrack',
    'ru_apc_m3_alt': 'M3A1 Halftrack',
    'ru_apc_mtlb': 'MT-LB',
    'ru_apc_mtlb_hmg': 'MT-LBVMK',
    'ru_apc_mtplb': 'MTP-LB',
    'ru_atm_shturm': '9P149 Shturm-S',
    'ru_atm_spandrel': '9P148 Spandrel',
    'ru_atm_spandrel_bf2': '9P148 Spandrel',
    'ru_ifv_ba6': 'BA-6',
    'ru_ifv_ba6_bf2': 'BA-6',
    'ru_ifv_bmp1': 'BMP-1',
    'ru_ifv_bmp1_bf2': 'BMP-1',
    'ru_ifv_bmp2': 'BMP-2',
    'ru_ifv_bmp2_bf2': 'BMP-2',
    'ru_ifv_bmp2m': 'BMP-2M',
    'ru_ifv_bmp2m_bf2': 'BMP-2M',
    'ru_ifv_bmp3': 'BMP-3',
    'ru_ifv_bmp3_bf2': 'BMP-3',
    'ru_ifv_bmp3m': 'BMP-3M',
    'ru_jep_ba64': 'BA-64',
    'ru_jep_brdm2': 'BRDM-2',
    'ru_jep_brdm2_alt': 'BRDM-2',
    'ru_jep_brdm2_support': 'BRDM-2 Support',
    'ru_jep_tigr': 'GAZ Tigr Support',
    'ru_jep_tigr_arbalet': 'GAZ Tigr Arbalet-DM',
    'ru_jep_tigr_pkp': 'GAZ Tigr',
    'ru_jep_tigr_rws': 'GAZ Tigr Arbalet-DM',
    'ru_jep_willysmb': 'Willys MB-2 Support',
    'ru_jep_willysmb_mg': 'Willys MB-2',
    'ru_jet_i16': 'I-16',
    'ru_jet_il2': 'IL-2',
    'ru_jet_la5fn': 'LA5FN',
    'ru_jet_mig21': 'MiG-21MF Fishbed',
    'ru_jet_mig29': 'MiG-29S Fulcrum',
    'ru_jet_mig29_asf': 'MiG-29S Fulcrum ASF',
    'ru_jet_mig29_sp': 'MiG-29S Fulcrum',
    'ru_jet_su25a': 'Su-25 Frogfoot',
    'ru_jet_su25a_sp': 'Su-25 Frogfoot',
    'ru_jet_su27': 'Su-27SM Flanker-B',
    'ru_jet_su27_asf': 'Su-27SM Flanker-B ASF',
    'ru_jet_su34': 'Su-34 Fullback',
    'ru_jet_su39': 'Su-39 Frogfoot',
    'ru_ship_andreev_lpd_atc': 'Aerial Recon',
    'ru_shp_lcvp': 'LCVP',
    'ru_shp_lcvp_bot': 'LCVP',
    'ru_shp_lcvp_logi': 'LCVP Logistics',
    'ru_shp_lcvp_logi_bot': 'LCVP Logistics',
    'ru_the_ka29t': 'KA-29',
    'ru_the_ka29t_gatling': 'KA-29',
    'ru_the_mi8': 'Mi-8MT Hip-C',
    'ru_the_mi8amtsh': 'Mi-8 AMTSh',
    'ru_tnk_bt7': 'BT-7',
    'ru_tnk_bt7_bf2': 'BT-7',
    'ru_tnk_t34': 'T-34 mod.1941',
    'ru_tnk_t34_85': 'T-34-85',
    'ru_tnk_t34_85_bf2': 'T-34-85',
    'ru_tnk_t34_bf2': 'T-34 mod.1941',
    'ru_tnk_t72': 'T-72A',
    'ru_tnk_t72_bf2': 'T-72A',
    'ru_tnk_t72_mgcupolabase': 'T-72',
    'ru_tnk_t72b': 'T-72B1',
    'ru_tnk_t72b_bf2': 'T-72B1',
    'ru_tnk_t72b_mgcupolabase': 'T-72',
    'ru_tnk_t90': 'T-90A',
    'ru_tnk_t90_alt': 'T-90A',
    'ru_tnk_t90_bf2': 'T-90A',
    'ru_tnk_t90_cupolabase': 'T-90',
    'ru_trk_kamaz_logistics': 'KamAZ-5350',
    'ru_trk_kamaz_support': 'KamAZ-4350',
    'ru_trk_logistics': 'Ural-4320 Logistics',
    'ru_trk_logistics_ww2': 'ZIS-5V Logistics',
    'ru_trk_support': 'Ural-4320',
    'ru_trk_support_ww2': 'ZIS-5V',
    'saf_aav_gopher': '9K35 Gopher',
    'saf_aav_shilka': 'ZSU-23-4 Shilka',
    'saf_aav_shilka_bf2': 'ZSU-23-4 Shilka',
    'saf_acv_btr60pu': 'Aerial Recon',
    'saf_ahe_mi24': 'Mi-24D Hind-D',
    'saf_ahe_mi24_sp': 'Mi-24D Hind-D',
    'saf_ahe_sa341l': 'SA 342L CAS',
    'saf_apc_bmp1': 'BMP-1',
    'saf_apc_bmp1_bf2': 'BMP-1',
    'saf_apc_bmp2': 'BMP-2',
    'saf_apc_bmp2_bf2': 'BMP-2',
    'saf_apc_btr60': 'BTR-60PB',
    'saf_apc_btr60_bf2': 'BTR-60PB',
    'saf_atm_uaz_spg': 'UAZ-3151 SPG-9',
    'saf_ifv_bmp1': 'BMP-1',
    'saf_ifv_bmp1_bf2': 'BMP-1',
    'saf_ifv_bmp2': 'BMP-2',
    'saf_ifv_bmp2_bf2': 'BMP-2',
    'saf_jep_brdm2': 'BRDM-2',
    'saf_jep_uaz': 'UAZ-469',
    'saf_jep_uaz_alt': 'UAZ-469 Support',
    'saf_jep_uaz_logistics': 'UAZ-469 Logistics',
    'saf_jep_uaz_mg': 'UAZ-469',
    'saf_jet_mig21': 'MiG-21MF Fishbed',
    'saf_jet_mig23': 'MiG-23MF Flogger-B',
    'saf_jet_mig29': 'MIG-29SM Fulcrum',
    'saf_jet_mig29_sp': 'MIG-29SM Fulcrum',
    'saf_jet_su22': 'Su-22M Fitter',
    'saf_jet_su22_sp': 'Su-22M Fitter',
    'saf_the_mi8': 'Mi-8T Hip-C',
    'saf_the_sa341l': 'SA 342L',
    'saf_tnk_t55': 'T-55',
    'saf_tnk_t55_bf2': 'T-55',
    'saf_tnk_t55_machinegunner': 'T-55',
    'saf_tnk_t62': 'T-62',
    'saf_tnk_t62_bf2': 'T-62',
    'saf_tnk_t62_cupolagunner': 'T-62',
    'saf_tnk_t72av': 'T-72AV',
    'saf_tnk_t72av_mgcupolabase': 'T-72',
    'saf_tnk_t72av_turms': 'T-72AV Turms-T',
    'saf_tnk_t72av_turms_bf2': 'T-72AV Turms-T',
    'saf_tnk_t72av_turms_mgcupolabase': 'T-72',
    'saf_tnk_t72m1': 'T-72M1',
    'saf_tnk_t72m1_bf2': 'T-72M1',
    'saf_tnk_t72m1_caged': 'T-72M1',
    'saf_tnk_t72m1_caged_mgcupolabase': 'T-72',
    'saf_tnk_t72m1_mgcupolabase': 'T-72',
    'saf_trk_logistics': 'Ural-4320 Logistics',
    'saf_trk_support': 'Ural-4320',
    'sam_sa3': 'SA-3 Goa',
    'sam_sa3_alt1': 'SA-3 Goa',
    'sam_sa3_atc': 'SA-3 Goa',
    'sam_sa3_atc_alt1': 'SA-3 Goa',
    'sam_tigercat': 'Tigercat SAM',
    'sam_tigercat_atc': 'Tigercat SAM',
    'shp_lcvp_rear_passengerlf': 'LCVP',
    'static_uav_1': 'UAV',
    'static_uav_2': 'UAV',
    'stationary_m252': 'M252',
    'the_chinook_sitting_l_passenger1': 'CH-147F Chinook',
    'the_mv22_seated_passenger1': 'MV-22 Osprey',
    'the_uh1d_medevac_right_floor_passenger': 'UH-1D Huey',
    'the_uh1n_leftside_position1': 'CH-135 Twin Huey',
    'the_uh1n_mg_passenger1': 'CH-135 Twin Huey',
    'the_uh1n_sp_passenger1': 'CH-135 Twin Huey',
    'tnk_merkava_passenger1': 'Merkava Mark IV',
    'trk_dumpster_pass1': 'Dumpster Truck',
    'us_aav_avenger': 'AN/TWQ-1 Avenger',
    'us_aav_m3': 'M3A1 Halftrack M45',
    'us_acv_lavc2': 'Aerial Recon',
    'us_acv_stryker': 'Aerial Recon',
    'us_acv_tent': 'Aerial Recon',
    'us_ahe_ah1z': 'AH-1 SuperCobra',
    'us_ahe_ah1z_sp': 'AH-1 SuperCobra',
    'us_ahe_ah6': 'AH-6 Littlebird Rockets',
    'us_ahe_ah6_sp': 'AH-6 Littlebird Rockets',
    'us_ahe_ah6a': 'AH-6 Littlebird',
    'us_ahe_apache': 'AH-64D Apache Longbow',
    'us_ahe_apache_sp': 'AH-64D Apache Longbow',
    'us_ahe_kiowa': 'OH-58D Kiowa Hydra/.50',
    'us_ahe_kiowa_alt': 'OH-58D Kiowa Hydra',
    'us_ahe_kiowa_alt2': 'OH-58D Kiowa Hellfire',
    'us_ahe_kiowa_alt_sp': 'OH-58D Kiowa Hydra',
    'us_ahe_kiowa_sp': 'OH-58D Kiowa Hydra/.50',
    'us_ahe_oh6': 'OH-6 Cayuse',
    'us_ahe_uh1c': 'UH-1C Huey',
    'us_ahe_uh1c_sp': 'UH-1C Huey',
    'us_ahe_uh1nrockets': 'UH-1N Twin Huey CAS',
    'us_ahe_uh1nrockets_sp': 'UH-1N Twin Huey CAS',
    'us_air_c47_para': 'Douglas C-47 Skytrain',
    'us_air_c47_para_sitting_l_passenger1': 'Douglas C-47 Skytrain',
    'us_apc_aavp7a1': 'AAVP7A1 RAM/RS',
    'us_apc_aavp7a1_bf2': 'AAVP7A1 RAM/RS',
    'us_apc_acav': 'M113 ACAV',
    'us_apc_lav25': 'LAV-25',
    'us_apc_lav25_bf2': 'LAV-25',
    'us_apc_m113': 'M113',
    'us_apc_m3': 'M3A1 Halftrack',
    'us_apc_stryker': 'M1126 Stryker ICV',
    'us_apc_stryker_mk19': 'M1126 Stryker ICV MK19',
    'us_atm_hmmwv': 'M1045A1 HMMWV TOW',
    'us_atm_hmmwv_uparmored': 'M1167 HMMWV Up-Armored TOW',
    'us_ifv_m2a2': 'M2A2 Bradley ODS',
    'us_ifv_m2a2_bf2': 'M2A2 Bradley ODS',
    'us_ifv_m8': 'M8 Greyhound',
    'us_ifv_m8_bf2': 'M8 Greyhound',
    'us_jep_hmmwv': 'M1025 HMMWV',
    'us_jep_hmmwv_crows': 'M1025 HMMWV CROWS',
    'us_jep_hmmwv_mk19': 'M1025 HMMWV MK19',
    'us_jep_hmmwv_support': 'M1038A1 HMMWV',
    'us_jep_hmmwv_uparmored': 'M1151 Up-Armored HMMWV',
    'us_jep_hmmwv_uparmored_alt': 'M1151 Up-Armored HMMWV',
    'us_jep_hmmwv_uparmored_crows': 'M1151 Up-Armored HMMWV CROWS',
    'us_jep_hmmwv_uparmored_mk19': 'M1151 Up-Armored HMMWV MK19',
    'us_jep_m151a2': 'M151A2',
    'us_jep_m151a2_support': 'M151A2 Support',
    'us_jep_willysmb': 'Willys MB-2 Support',
    'us_jep_willysmb_mg': 'Willys MB-2',
    'us_jet_a10a': 'A-10A Thunderbolt II',
    'us_jet_a10a_sp': 'A-10A Thunderbolt II',
    'us_jet_a1h': 'A-1H Skyraider',
    'us_jet_a4': 'A-4C Skyhawk',
    'us_jet_f15': 'F-15E Strike Eagle',
    'us_jet_f16': 'F-16C Fighting Falcon',
    'us_jet_f16_sp': 'F-16C Fighting Falcon',
    'us_jet_f18c': 'F/A-18C Hornet',
    'us_jet_harrier': 'AV-8B Harrier II+',
    'us_jet_harrier_sp': 'AV-8B Harrier II+',
    'us_jet_harrierb': 'AV-8B Harrier II+ CAS',
    'us_jet_p47d': 'P-47D Thunderbolt',
    'us_jet_p51d': 'P-51D Mustang',
    'us_m1': '76mm M5',
    'us_m51': 'M51 Quadmount',
    'us_shp_lcvp': 'LCVP',
    'us_shp_lcvp_bot': 'LCVP',
    'us_shp_lcvp_logi': 'LCVP Logistics',
    'us_shp_lcvp_logi_bot': 'LCVP Logistics',
    'us_shp_pbr': 'Patrol Boat-River',
    'us_shp_swiftboat': 'US Swift Boat',
    'us_the_chinook': 'CH-47D Chinook',
    'us_the_h-34': 'H-34 Choctaw',
    'us_the_mh6': 'MH-6 Littlebird',
    'us_the_mv22': 'MV-22 Osprey',
    'us_the_uh1c': 'UH-1C Huey',
    'us_the_uh1c_sp': 'UH-1C Huey',
    'us_the_uh1d': 'UH-1D Huey',
    'us_the_uh1d_medevac': 'UH-1D Huey',
    'us_the_uh1n': 'UH-1N Twin Huey',
    'us_the_uh1n_m240d': 'UH-1N Twin Huey',
    'us_the_uh1n_sp': 'UH-1N Twin Huey',
    'us_the_uh60': 'UH-60L Blackhawk',
    'us_the_uh60_alt': 'UH-60L Blackhawk',
    'us_the_uh60_soar': 'MH-60L Blackhawk',
    'us_the_uh60_sp': 'UH-60L Blackhawk',
    'us_tnk_m10': 'M10 tank destroyer',
    'us_tnk_m10_bf2': 'M10 tank destroyer',
    'us_tnk_m1a1': 'M1A1 Abrams',
    'us_tnk_m1a1_alt': 'M1A1 Abrams TUSK',
    'us_tnk_m1a1_bf2': 'M1A1 Abrams',
    'us_tnk_m1a1_m2cupolabase': 'M1A1 Abrams',
    'us_tnk_m1a2': 'M1A2 Abrams',
    'us_tnk_m1a2_alt': 'M1A2 Abrams TUSK',
    'us_tnk_m1a2_bf2': 'M1A2 Abrams',
    'us_tnk_m1a2_m2cupolabase': 'M1A2 Abrams',
    'us_tnk_m48a1': 'M48A1 Patton',
    'us_tnk_m4a3_75mm': 'M4A3 75mm',
    'us_tnk_m4a3_75mm_bf2': 'M4A3 75mm',
    'us_tnk_m4a3_75mm_cupola_gunner': 'M4A3 75mm',
    'us_tnk_m4a3_75mm_dwg': 'M4A3 75mm DWG',
    'us_tnk_m4a3_75mm_dwg_bf2': 'M4A3 75mm DWG',
    'us_tnk_m4a3_75mm_dwg_cupola_gunner': 'M4A3 75mm',
    'us_tnk_m67': 'M67 Zippo',
    'us_trk_logistics': 'M35 Logistics',
    'us_trk_logistics_ww2': 'GMC CCKW Logistics',
    'us_trk_m35': 'M35 2.5 Ton',
    'us_trk_m548a1': 'M548A1',
    'us_trk_support': 'M35 2.5 Ton',
    'us_trk_support_ww2': 'GMC CCKW',
    'usaas_stinger': 'Stinger',
    'vc_shp_sampan': 'Sampan',
    'wasp_defence_back': 'Wasp',
    'wasp_defence_front': 'Wasp',
    'zis3': 'ZiS-3',
    'zis3_sp': 'ZiS-3',
    'zpu4': 'ZPU-4',
    'zpu4_atc': 'ZPU-4',
    'zu232': 'ZU-23-2',
    'zu232_mounted': 'ZSU-23-2',
}
