"""Mapping from raw PR kit names to canonical kit categories.

Raw kit names from demos: 'usa_rifleman_ziptie', 'pl_medic_ziptie',
'taliban_medic', 'ru_assault_alt_iron', 'gungame_blue_rif_scope_6', etc.

All faction variants (us_, fr_, ru_, pl_, gb_, ch_, taliban_, insrg_, mec_, etc.)
and suffixes (_ziptie, _alt, _iron, _scope, _idx*) are normalized to the same
base kit. E.g. us_rifleman_ziptie, fr_rifleman, ru_rifleman_alt = "Fusilero".
"""

import os
import json
import logging
from typing import Optional

logger = logging.getLogger(__name__)

# (keyword, readable_name, emoji_name, asset_file)
# Order matters — first match wins. More specific keywords first.
KIT_CATEGORIES = [
    ("sniper", "Sniper", "pr_sniper", "kit_Sniper.png"),
    ("marksman", "Tirador", "pr_marksman", "kit_Marksman.png"),
    ("spotter", "Observador", "pr_spotter", "kit_Spotter.png"),
    ("medic", "Medico", "pr_medic", "kit_Medic.png"),
    ("officer", "Oficial", "pr_officer", "kit_Officer.png"),
    ("grenadier", "Granadero", "pr_grenadier", "kit_Grenadier.png"),
    ("breacher", "Breacher", "pr_engineer", "kit_Engineer.png"),
    ("machine_gun", "Ametralladora", "pr_mg", "kit_MG.png"),
    ("mg", "Ametralladora", "pr_mg", "kit_MG.png"),
    ("combat_engineer", "Ing. Combate", "pr_engineer", "kit_Engineer.png"),
    ("engineer", "Ingeniero", "pr_engineer", "kit_Engineer.png"),
    ("crewman", "Tripulante", "pr_crewman", "kit_Crewman.png"),
    ("pilot", "Piloto", "pr_pilot", "kit_Pilot.png"),
    ("specop", "Fuerzas Esp.", "pr_specops", "kit_Specops.png"),
    ("recon", "Reconocimiento", "pr_recon", "kit_recon.png"),
    ("aa", "Anti-Aereo", "pr_aa", "kit_AA.png"),
    ("hat", "HAT", "pr_at", "kit_AT.png"),
    ("lat", "LAT", "pr_at", "kit_AT.png"),
    ("anti-tank", "Anti-Tanque", "pr_at", "kit_AT.png"),
    ("at", "Anti-Tanque", "pr_at", "kit_AT.png"),
    ("rifleman_ap", "Fusilero AP", "pr_rifle", "kit_Rifle.png"),
    ("automatic_rifle", "Fus. Automatico", "pr_mg", "kit_MG.png"),
    ("assault", "Asalto", "pr_assault", "kit_Light_Assault.png"),
    ("rifleman", "Fusilero", "pr_rifle", "kit_Rifle.png"),
    ("rifle", "Fusilero", "pr_rifle", "kit_Rifle.png"),
    ("unarmed", "Desarmado", "pr_rifle", "kit_Rifle.png"),
]

_emoji_cache: dict[str, str] = {}
_EMOJI_FILE = "bot/data/kit_emojis.json"

# Humanized aliases generated by the scraper (graphs/demos/aliases.json). Single
# source of truth shared with the web. clean_*/classify_kit consult this first and
# only fall back to the heuristics below when a code is absent (e.g. brand-new
# content not yet in the manifest).
_aliases: dict = {}
_ALIASES_LOCAL = "graphs/demos/aliases.json"


def set_aliases(data: dict) -> None:
    global _aliases
    if isinstance(data, dict):
        _aliases = data
        logger.info("Loaded asset aliases: %s",
                    ", ".join(f"{k}:{len(v)}" for k, v in data.items()))


async def load_aliases() -> None:
    """Load aliases.json from GitHub Pages (fresh), falling back to the bundled
    local copy. Non-fatal: heuristics still work if both fail."""
    try:
        import aiohttp
        from bot.config import BASE_URL
        url = f"{BASE_URL}/graphs/demos/aliases.json"
        async with aiohttp.ClientSession() as s:
            async with s.get(url, timeout=aiohttp.ClientTimeout(total=10)) as r:
                if r.status == 200:
                    set_aliases(await r.json(content_type=None))
                    return
    except Exception as exc:
        logger.warning("No se pudo bajar aliases.json (%s); uso copia local.", exc)
    try:
        with open(_ALIASES_LOCAL, encoding="utf-8") as f:
            set_aliases(json.load(f))
    except Exception as exc:
        logger.warning("aliases.json local no disponible (%s); uso heurísticas.", exc)


def classify_kit(raw_name: str) -> tuple[str, str, str]:
    """Classify a raw kit name into (readable_name, emoji_name, asset_file).

    Uses the generated aliases for the readable role label when available (so no
    kit falls back to "Otro"); the emoji/asset still come from the keyword match.
    """
    lower = raw_name.lower()
    alias = _aliases.get("kits", {}).get(raw_name)
    emoji_name, asset = "pr_rifle", "kit_Rifle.png"
    if "gungame" not in lower:
        for keyword, _readable, e_name, a in KIT_CATEGORIES:
            if keyword in lower:
                emoji_name, asset = e_name, a
                break
    if alias:
        return (alias, emoji_name, asset)
    if "gungame" in lower:
        return ("Gungame", "pr_rifle", "kit_Rifle.png")
    for keyword, readable, e_name, a in KIT_CATEGORIES:
        if keyword in lower:
            return (readable, e_name, a)
    return ("Otro", "pr_rifle", "kit_Rifle.png")


def get_kit_display(raw_name: str) -> str:
    """Get 'emoji ReadableName' for a raw kit name."""
    readable, emoji_name, _ = classify_kit(raw_name)
    emoji = _emoji_cache.get(emoji_name, "")
    return f"{emoji} {readable}" if emoji else readable


def normalize_kits(kits_dict: dict[str, int]) -> dict[str, int]:
    """Normalize a {raw_kit: count} dict by grouping faction variants.

    E.g. {'us_rifleman_ziptie': 5, 'fr_rifleman': 3, 'us_medic': 2}
    → {'Fusilero': 8, 'Medico': 2}
    """
    normalized: dict[str, int] = {}
    for raw, count in kits_dict.items():
        readable, _, _ = classify_kit(raw)
        normalized[readable] = normalized.get(readable, 0) + count
    return normalized


def get_kit_emoji(readable_name: str) -> str:
    """Get just the emoji string for a readable kit name (for inline use)."""
    for _, readable, emoji_name, _ in KIT_CATEGORIES:
        if readable == readable_name:
            return _emoji_cache.get(emoji_name, "")
    return ""


def load_emoji_cache() -> None:
    global _emoji_cache
    if os.path.exists(_EMOJI_FILE):
        with open(_EMOJI_FILE) as f:
            _emoji_cache.update(json.load(f))
        logger.info("Loaded %d kit emojis from cache.", len(_emoji_cache))


def save_emoji_cache() -> None:
    os.makedirs(os.path.dirname(_EMOJI_FILE), exist_ok=True)
    with open(_EMOJI_FILE, "w") as f:
        json.dump(_emoji_cache, f, indent=2)


def update_emoji_cache(emoji_name: str, emoji_str: str) -> None:
    _emoji_cache[emoji_name] = emoji_str
    save_emoji_cache()


def clean_weapon_name(raw: str) -> str:
    """Clean a raw weapon name into something readable.

    'usrif_m4scope' → 'M4 Scope'
    'gerlmg_mg34' → 'MG34'
    'apc_aavp7a1_PrimaryGun' → 'AAVP7A1'
    'ushgr_m67' → 'M67'
    """
    alias = _aliases.get("weapons", {}).get(raw)
    if alias:
        return alias.get("label") or alias.get("model") or raw
    import re
    name = raw
    # Strip faction+type prefix: usrif_, rulmg_, gerlmg_, plrif_, insrg_, hmg_, etc.
    name = re.sub(
        r'^(?:us|ru|gb|ge|ch|pl|fr|mec|cf|mil|ins(?:rg)?|taliban|fsa|hamas|arf|ger|idf|nl|nva|vnnva|aus|arg|cdn|nz)?'
        r'(?:rif|lmg|mmg|hmg|smg|hgr|pis|sni|shg|at|aa|mg|car|rl|gl|apc|tnk|ahe|the|jet)?_?',
        '', name, flags=re.IGNORECASE
    )
    # Strip common suffixes
    name = re.sub(r'_?(?:deployed|scope|scopedeployed|iron|alt|idx\d+|gun|_r|_g|PrimaryGun|Coax_r|Coax_g|Maingun)$', '', name, flags=re.IGNORECASE)
    # Clean up
    name = name.strip('_').replace('_', ' ')
    if not name:
        name = raw.split('_')[-1]
    # Capitalize: short = uppercase, long = title
    if len(name) <= 6:
        name = name.upper()
    else:
        name = name.title()
    return name


def weapon_kind(raw: str) -> str:
    """Tipo de arma (rifle/LMG/sniper/grenade/vehicle/unknown…) según el alias."""
    return _aliases.get("weapons", {}).get(raw, {}).get("kind", "unknown")


def is_personal_weapon(raw: str) -> bool:
    """True si es un arma personal (excluye entorno '?' y armas de vehículo), para
    no contaminar el 'arma favorita'/top de un jugador con cañones de blindado.

    Si los aliases no están cargados (fetch falló) no se puede saber el kind, así
    que solo se descarta '?' — degradar mostrando de más es mejor que vaciar la
    lista por completo."""
    if raw == "?":
        return False
    if not _aliases.get("weapons"):
        return True
    return weapon_kind(raw) not in ("vehicle", "unknown")


def weapon_vehicle_name(raw: str) -> Optional[str]:
    """Vehículo/emplazamiento que porta un arma montada (p.ej. 'apc_btr80_barrelgun'
    → 'BTR-80'), o None si no es arma de vehículo. Lo provee el alias."""
    return _aliases.get("weapons", {}).get(raw, {}).get("vehicle")


def weapon_vclass(raw: str) -> Optional[str]:
    """'vehicle' (vehículo tripulado) | 'emplacement' (estático/desplegable) | None."""
    return _aliases.get("weapons", {}).get(raw, {}).get("vclass")


def is_vehicle_kill(raw: str) -> bool:
    """True si la kill se logró con el arma de un vehículo tripulado (no a pie, no
    emplazamiento). Base honesta para 'kills con vehículos'."""
    return weapon_vclass(raw) == "vehicle"


def weapon_vtype(raw: str) -> Optional[str]:
    """Categoría amplia del arma de vehículo: 'ground'|'air'|'naval'|'emplacement',
    o None si es un arma personal/desconocida."""
    return _aliases.get("weapons", {}).get(raw, {}).get("vtype")


def weapon_category(raw: str) -> str:
    """Clasifica CUALQUIER code de arma en una categoría de asset para el desglose:
    'infantry' (a pie) | 'ground' | 'air' | 'naval' | 'emplacement' | 'env' (entorno)."""
    if raw == "?":
        return "env"
    vt = weapon_vtype(raw)
    if vt:
        return vt
    return "infantry"


def weapon_model_name(raw: str) -> str:
    """Modelo del arma SIN la variante (agrupa accesorios): 'rurif_ak74m_1p78' →
    'AK-74M'. Para colapsar variantes en los gráficos/listas del bot."""
    alias = _aliases.get("weapons", {}).get(raw)
    if alias and alias.get("model"):
        return alias["model"]
    return clean_weapon_name(raw)


def clean_vehicle_name(raw: str) -> str:
    """Clean a raw vehicle name: 'us_tnk_m1a2' → 'M1A2', 'ru_apc_bmp2' → 'BMP2'."""
    alias = _aliases.get("vehicles", {}).get(raw)
    if alias:
        return alias.get("label") or alias.get("model") or raw
    import re
    name = raw
    # Strip faction prefix
    name = re.sub(
        r'^(?:us|ru|gb|ge|ch|pl|fr|mec|cf|mil|ins(?:rg)?|taliban|fsa|hamas|idf|nl|nva|aus|arg|cdn|nz)_',
        '', name, flags=re.IGNORECASE
    )
    # Strip vehicle type prefix
    name = re.sub(
        r'^(?:tnk|apc|ifv|jep|trk|shp|the|ahe|aav|atm|box|jet|aav)_',
        '', name, flags=re.IGNORECASE
    )
    name = name.strip('_').replace('_', ' ')
    if not name:
        name = raw.split('_')[-1]
    if name.isupper() or name.islower():
        name = name.upper() if len(name) <= 6 else name.title()
    return name


_SEAT_FALLBACK = {
    "driver": "Conductor", "pilot": "Piloto", "copilot": "Copiloto",
    "co-pilot": "Copiloto", "gunner": "Artillero", "passenger": "Pasajero",
    "commander": "Comandante",
}


def clean_seat(raw: str) -> str:
    """Nombre legible de un asiento de vehículo ('gunner' → 'Artillero')."""
    alias = _aliases.get("seats", {}).get(raw)
    if alias:
        return alias
    low = (raw or "").lower()
    for key, label in _SEAT_FALLBACK.items():
        if key in low:
            return label
    return (raw or "Asiento").replace("_", " ").title()


def clean_map_name(raw: str) -> str:
    """Clean a raw map name: 'albasrah_2' → 'Al Basrah'."""
    alias = _aliases.get("maps", {}).get(raw)
    if alias:
        return alias
    return raw.replace('_', ' ').title()


def clean_gamemode(raw: str) -> str:
    """Nombre legible del gamemode: 'gpm_cq' → 'AAS', 'gpm_insurgency' → 'Insurgencia'."""
    alias = _aliases.get("gamemodes", {}).get(raw)
    if alias:
        return alias
    return raw.replace('gpm_', '').replace('_', ' ').upper() or "—"


def get_all_assets() -> list[tuple[str, str]]:
    seen = set()
    assets = []
    for _, _, emoji_name, asset_file in KIT_CATEGORIES:
        if emoji_name not in seen:
            seen.add(emoji_name)
            path = os.path.join("bot", "assets", "kits", asset_file)
            if os.path.exists(path):
                assets.append((emoji_name, path))
    return assets
